/**
 * Generates base64 blurDataURL placeholders for every project image
 * in `public/projects/`. Writes the result as a TypeScript module so
 * the placeholders can be imported at build time — no runtime overhead.
 *
 * Usage:  npx tsx scripts/generate-blur.ts
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = dirname(fileURLToPath(import.meta.url));

interface BlurMap {
  [filename: string]: string;
}

const SRC_DIR = resolve(__dirname, "../public/projects");
const OUT_FILE = resolve(__dirname, "../src/lib/blur-data.ts");

async function main() {
  const files = readdirSync(SRC_DIR).filter((f) =>
    /\.(png|jpe?g|webp|avif)$/i.test(f),
  );

  if (files.length === 0) {
    console.log("No project images found — skipping blur generation.");
    return;
  }

  const map: BlurMap = {};

  for (const file of files) {
    const buf = readFileSync(resolve(SRC_DIR, file));
    const jpegBuf = await sharp(buf)
      .resize(16, 12, { fit: "cover" })
      .jpeg({ quality: 30 })
      .toBuffer();

    map[file] = `data:image/jpeg;base64,${jpegBuf.toString("base64")}`;
    console.log(`  ✓ ${file}  (${jpegBuf.length} bytes)`);
  }

  const lines = [
    "// Auto-generated by scripts/generate-blur.ts — do not edit manually.",
    `// Generated on ${new Date().toISOString().split("T")[0]}`,
    "",
    `export const blurData: Record<string, string> = ${JSON.stringify(map, null, 2)};`,
    "",
  ];

  writeFileSync(OUT_FILE, lines.join("\n"), "utf-8");
  console.log(`\nWrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
